# Generated by Django 4.0.7 on 2022-09-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.FloatField()),
                ('Entitled', models.CharField(max_length=30, unique=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('Login', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=4)),
            ],
            options={
                'unique_together': {('Login', 'Password')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionId', models.CharField(max_length=30, unique=True)),
                ('Note', models.CharField(blank=True, max_length=100, null=True)),
                ('TransactionDate', models.DateTimeField(auto_now_add=True)),
                ('CustomerFullName', models.CharField(max_length=50)),
                ('Output', models.FloatField(blank=True, null=True)),
                ('Input', models.FloatField(blank=True, null=True)),
                ('Currency', models.FloatField()),
                ('Credit', models.FloatField()),
                ('AccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agency.account')),
            ],
        ),
    ]
