# Generated by Django 4.1.1 on 2022-09-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='AccountId',
            new_name='Account',
        ),
    ]
