# Generated by Django 4.1.1 on 2022-09-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0002_rename_accountid_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='MRU', max_length=30),
        ),
    ]
