# Generated by Django 4.1.1 on 2022-10-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0003_account_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recu',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
