# Generated by Django 4.1.1 on 2022-10-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0005_transaction_currencyname_alter_transaction_recu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='CurrencyName',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
